In [1]:
import tensorflow as tf
import re
from functools import partial
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
import os
from google.colab import drive
from google.colab import files

In [ ]:
MOUNTPOINT = '/content/gdrive'
DATADIR = os.path.join(MOUNTPOINT, 'My Drive', 'Learn TensorFlow', 'Data')
drive.mount(MOUNTPOINT)

Mounted at /content/gdrive


In [ ]:
path = os.path.join(DATADIR, 'training_twitter_data.csv')
data = pd.read_csv(path, encoding='cp1252')
data

0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  \
0        0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
1        0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
2        0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
3        0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4        0  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY   
...     ..         ...                           ...       ...   
1599994  4  2193601966  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599995  4  2193601969  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599996  4  2193601991  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599997  4  2193602064  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599998  4  2193602129  Tue Jun 16 08:40:50 PDT 2009  NO_QUERY   

         _TheSpecialOne_  \
0          scotthamilton   
1               mattycus   
2                ElleCTF   
3                 Karoli   
4               joy_wolf   
...                  ...   
1599994  AmandaMarie1028   
1599995      TheWDBoards   
1599996           bpbabe   
1599997     tinydiamondz   
1599998   RyanTrevMorris   

        @switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D  
0        is upset that he can't update his Facebook by ...                                                                   
1        @Kenichan I dived many times for the ball. Man...                                                                   
2          my whole body feels itchy and like its on fire                                                                    
3        @nationwideclass no, it's not behaving at all....                                                                   
4                            @Kwesidei not the whole crew                                                                    
...                                                    ...                                                                   
1599994  Just woke up. Having no school is the best fee...                                                                   
1599995  TheWDB.com - Very cool to hear old Walt interv...                                                                   
1599996  Are you ready for your MoJo Makeover? Ask me f...                                                                   
1599997  Happy 38th Birthday to my boo of alll time!!! ...                                                                   
1599998  happy #charitytuesday @theNSPCC @SparksCharity...                                                                   

[1599999 rows x 6 columns]

In [ ]:
tr_data = data.copy()

In [ ]:
tr_data.columns = ['col0', 'col1', 'col2', 'col3', 'col4', 'col5']
tr_data

col0        col1                          col2      col3  \
0           0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
1           0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
2           0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
3           0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4           0  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY   
...       ...         ...                           ...       ...   
1599994     4  2193601966  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599995     4  2193601969  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599996     4  2193601991  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599997     4  2193602064  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599998     4  2193602129  Tue Jun 16 08:40:50 PDT 2009  NO_QUERY   

                    col4                                               col5  
0          scotthamilton  is upset that he can't update his Facebook by ...  
1               mattycus  @Kenichan I dived many times for the ball. Man...  
2                ElleCTF    my whole body feels itchy and like its on fire   
3                 Karoli  @nationwideclass no, it's not behaving at all....  
4               joy_wolf                      @Kwesidei not the whole crew   
...                  ...                                                ...  
1599994  AmandaMarie1028  Just woke up. Having no school is the best fee...  
1599995      TheWDBoards  TheWDB.com - Very cool to hear old Walt interv...  
1599996           bpbabe  Are you ready for your MoJo Makeover? Ask me f...  
1599997     tinydiamondz  Happy 38th Birthday to my boo of alll time!!! ...  
1599998   RyanTrevMorris  happy #charitytuesday @theNSPCC @SparksCharity...  

[1599999 rows x 6 columns]

In [ ]:
tr_data = tr_data.drop(columns=['col2', 'col3', 'col4'])
tr_data

col0        col1                                               col5
0           0  1467810672  is upset that he can't update his Facebook by ...
1           0  1467810917  @Kenichan I dived many times for the ball. Man...
2           0  1467811184    my whole body feels itchy and like its on fire 
3           0  1467811193  @nationwideclass no, it's not behaving at all....
4           0  1467811372                      @Kwesidei not the whole crew 
...       ...         ...                                                ...
1599994     4  2193601966  Just woke up. Having no school is the best fee...
1599995     4  2193601969  TheWDB.com - Very cool to hear old Walt interv...
1599996     4  2193601991  Are you ready for your MoJo Makeover? Ask me f...
1599997     4  2193602064  Happy 38th Birthday to my boo of alll time!!! ...
1599998     4  2193602129  happy #charitytuesday @theNSPCC @SparksCharity...

[1599999 rows x 3 columns]

In [ ]:
tr_data.columns = ['Sentiment', 'ID', 'Text']
tr_data

Sentiment          ID  \
0                0  1467810672   
1                0  1467810917   
2                0  1467811184   
3                0  1467811193   
4                0  1467811372   
...            ...         ...   
1599994          4  2193601966   
1599995          4  2193601969   
1599996          4  2193601991   
1599997          4  2193602064   
1599998          4  2193602129   

                                                      Text  
0        is upset that he can't update his Facebook by ...  
1        @Kenichan I dived many times for the ball. Man...  
2          my whole body feels itchy and like its on fire   
3        @nationwideclass no, it's not behaving at all....  
4                            @Kwesidei not the whole crew   
...                                                    ...  
1599994  Just woke up. Having no school is the best fee...  
1599995  TheWDB.com - Very cool to hear old Walt interv...  
1599996  Are you ready for your MoJo Makeover? Ask me f...  
1599997  Happy 38th Birthday to my boo of alll time!!! ...  
1599998  happy #charitytuesday @theNSPCC @SparksCharity...  

[1599999 rows x 3 columns]

In [ ]:
X_train_init = tr_data.drop(columns=['Sentiment', 'ID'])
X_train_init

Text
0        is upset that he can't update his Facebook by ...
1        @Kenichan I dived many times for the ball. Man...
2          my whole body feels itchy and like its on fire 
3        @nationwideclass no, it's not behaving at all....
4                            @Kwesidei not the whole crew 
...                                                    ...
1599994  Just woke up. Having no school is the best fee...
1599995  TheWDB.com - Very cool to hear old Walt interv...
1599996  Are you ready for your MoJo Makeover? Ask me f...
1599997  Happy 38th Birthday to my boo of alll time!!! ...
1599998  happy #charitytuesday @theNSPCC @SparksCharity...

[1599999 rows x 1 columns]

In [ ]:
binencoder = LabelBinarizer()
y_train_init = tr_data['Sentiment']
y_train_init = y_train_init.astype(int)
y_train_init = binencoder.fit_transform(y_train_init)
y_train_init

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [ ]:
X_train_init.isnull().sum()

Text    0
dtype: int64

In [ ]:
def clean(text):
    text = str(text).lower()
    text = re.sub(r'https?:\/\/\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

X_train_init['Text'] = X_train_init['Text'].apply(clean)
X_train_init

Text
0        is upset that he cant update his facebook by t...
1        kenichan i dived many times for the ball manag...
2          my whole body feels itchy and like its on fire 
3        nationwideclass no its not behaving at all im ...
4                             kwesidei not the whole crew 
...                                                    ...
1599994  just woke up having no school is the best feel...
1599995  thewdbcom  very cool to hear old walt intervie...
1599996  are you ready for your mojo makeover ask me fo...
1599997  happy th birthday to my boo of alll time tupac...
1599998  happy charitytuesday thenspcc sparkscharity sp...

[1599999 rows x 1 columns]

In [ ]:
X_train_full, X_test, y_train_full, y_test = train_test_split(X_train_init,
                                                    y_train_init,
                                                    test_size=0.1,
                                                    shuffle=True,
                                                    random_state=42)

In [ ]:
X_train_full
X_test
y_train_full
y_test

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [ ]:
X_train_df, y_train = X_train_full[:-50000], y_train_full[:-50000]
X_valid_df, y_valid = X_train_full[-50000:], y_train_full[-50000:]

In [ ]:
X_train_df
X_valid_df
y_train
y_valid

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
num_y_train_zeros = 0
num_y_train_ones = 0

for i in range(len(y_train)):
  if y_train[i][0] == 0:
    num_y_train_zeros += 1
  else:
    num_y_train_ones += 1

print(num_y_train_zeros)
print(num_y_train_ones)

num_y_valid_zeros = 0
num_y_valid_ones = 0

for i in range(len(y_valid)):
  if y_valid[i][0] == 0:
    num_y_valid_zeros += 1
  else:
    num_y_valid_ones += 1

print(num_y_valid_zeros)
print(num_y_valid_ones)

695005
694994
25182
24818


In [ ]:
X_train = tf.data.Dataset.from_tensor_slices(X_train_df.to_dict(orient="list"))
X_valid = tf.data.Dataset.from_tensor_slices(X_valid_df.to_dict(orient="list"))

In [ ]:
vocab_size = 10000
text_vec_layer = tf.keras.layers.TextVectorization(max_tokens=vocab_size)
text_vec_layer.adapt(X_train.map(lambda x: x['Text']))

In [ ]:
text_vec_model_2 = tf.keras.Sequential([
    tf.keras.Input(shape=(1,), dtype=tf.string),
    text_vec_layer
])

In [ ]:
tf.random.set_seed(42)

In [ ]:
embed_size = 2048

model = tf.keras.Sequential([
    text_vec_layer,
    tf.keras.layers.Embedding(vocab_size, embed_size, mask_zero=True),
    tf.keras.layers.GRU(256),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

In [ ]:
lr_schedule = tf.keras.optimizers.schedules.InverseTimeDecay(
    initial_learning_rate=0.01,
    decay_steps=10_000,
    decay_rate=1.0,
    staircase=False
)

In [ ]:
lr_schedule_optimizer = tf.keras.optimizers.SGD(
    learning_rate=lr_schedule,
    momentum=0.9,
    nesterov=True
)

model.compile(
    loss="binary_crossentropy",
    optimizer=lr_schedule_optimizer,
    metrics=["accuracy"]
)

In [ ]:
checkpoint_cb = tf.keras.callbacks.ModelCheckpoint("my_checkpoints.weights.h5", save_weights_only=True)
early_stopping_cb = tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)

In [ ]:
# train_dataset = tf.data.Dataset.from_tensor_slices((X_train_df.to_dict(orient="list"), y_train))

train_dataset = tf.data.Dataset.from_tensor_slices((X_train_df['Text'].values, y_train))

In [ ]:
# valid_dataset = tf.data.Dataset.from_tensor_slices((X_valid_df.to_dict(orient="list"), y_valid))

valid_dataset = tf.data.Dataset.from_tensor_slices((X_valid_df['Text'].values, y_valid))

In [ ]:
print("Training dataset:")
for element in train_dataset:
    print(element)
    break  # Print only the first element

print("\nValidation dataset:")
for element in valid_dataset:
    print(element)
    break  # Print only the first element

Training dataset:
(<tf.Tensor: shape=(), dtype=string, numpy=b'just saw your picture and my heart melted '>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>)

Validation dataset:
(<tf.Tensor: shape=(), dtype=string, numpy=b'antonea absolutely i gave ya  stars on it too '>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>)


In [ ]:
history = model.fit(
    train_dataset.batch(32).prefetch(1),
    validation_data=valid_dataset.batch(32).prefetch(1),
    epochs=5,
    callbacks=[checkpoint_cb, early_stopping_cb]
)

In [ ]:
model.save('sentiment_analysis_model.keras')

In [ ]:
model.save('sentiment_analysis_model_tf', save_format='tf')

In [ ]:
sentiment_analysis_model = tf.keras.models.load_model('sentiment_analysis_model.keras')

In [ ]:
test_dataset = tf.data.Dataset.from_tensor_slices((X_test['Text'].values, y_test))

In [ ]:
model.evaluate(test_dataset.batch(32))

5000/5000 [==============================] - 26s 5ms/step - loss: 0.4049 - accuracy: 0.8168


[0.40490204095840454, 0.8168062567710876]